- src/components/Roles/Role/Modals/RoleManagerChangesModal.tsx
Fixes issue where member tokens were not being minted during role creation
> Fix minting role tokens

- src/components/Roles/Role/Modals/RoleManagerChangesModal.tsx
- src/graphql/agreements.tsx
Fixes incorrect parameter in bulk burn agreement tokens api call
> fix: burning role tokens

- src/components/Roles/Role/Modals/RoleAddMembersModal.tsx
- src/components/Roles/Role/Modals/RoleManagerChangesModal.tsx
- src/components/Roles/Role/RolesManagerMembers.tsx
Role changes modal actually works correctly now
> Working role changes modal

- src/components/Admin/Tabs/AdminAgreementDetails.tsx
- src/components/Admin/Tabs/AdminAgreementExtensions.tsx
- src/components/Admin/Tabs/AdminContractManagement.tsx
- src/components/Admin/Tabs/AdminMembershipRequirements.tsx
- src/components/Admin/Tabs/AdminMembershipSettings.tsx
- src/components/Admin/Tabs/AdminRoles.tsx
- src/components/AgreementHome/CoreWidgets/AgreementBlankSlateWidget.tsx
- src/components/Developer/DeveloperPortalButton.tsx
- src/components/Header/MeemFAQModal.tsx
- src/components/Profile/Tabs/Identity/ManageIdentity.tsx
- src/components/Styles/MeemTheme.tsx
Modal for developer documentation and information
> Developer modal

- src/components/AgreementHome/AgreementDetailsModal.tsx
- src/components/AgreementHome/CoreWidgets/AgreementAddMoreExtensionsWidget.tsx
- src/components/AgreementHome/CoreWidgets/AgreementInfoWidget.tsx
Agreement details modal which replaces the existing contract address copy link on AgreementInfoWidget
> Agreement details modal

- exampleextension/components/Example/ExampleWidget.tsx
- src/components/Admin/AgreementAdmin.tsx
- src/components/Admin/Tabs/AdminAgreementExtensions.tsx
- src/components/Admin/Tabs/AdminRoles.tsx
- src/components/AgreementHome/CoreWidgets/AgreementAddMoreExtensionsWidget.tsx
- src/components/AgreementHome/CoreWidgets/AgreementInfoWidget.tsx
- src/components/AgreementHome/CoreWidgets/AgreementMembersWidget.tsx
- src/components/AgreementHome/CoreWidgets/AgreementRequirementsWidget.tsx
- src/components/AgreementHome/Members/AgreementMembers.tsx
- src/components/Extensions/Discussion/DiscussionHome.tsx
- src/components/Extensions/Discussion/DiscussionPostPreview.tsx
- src/components/Extensions/Discussion/DiscussionPostSubmit.tsx
- src/components/Extensions/Discussion/DiscussionSettings.tsx
- src/components/Extensions/Discussion/DiscussionWidget.tsx
- src/components/Extensions/ExtensionBlankSlate.tsx
- src/components/Extensions/ExtensionPageHeader.tsx
- src/components/Extensions/Guild/GuildExtensionSettings.tsx
- src/components/Extensions/Guild/GuildWidget.tsx
- src/components/Extensions/Steward/StewardWidget.tsx
- src/components/Header/Header.tsx
- src/components/Profile/Profile.tsx
- src/components/Profile/Tabs/MyAgreements.tsx
- src/components/Roles/RolesManager.tsx
Several bug fixes to page navigation
> Late jan fixes

- src/components/Admin/AgreementAdminChangesModal.tsx
- src/components/Admin/Modals/ChangeMeemProtocolPermissionsModal.tsx
- src/components/Admin/Modals/CreateSafeModal.tsx
- src/components/Admin/Modals/RemoveMemberModal.tsx
- src/components/Admin/Tabs/AdminAgreementDetails.tsx
- src/components/Admin/Tabs/AdminAgreementIcon.tsx
- src/components/Admin/Tabs/AdminContractManagement.tsx
- src/components/Admin/Tabs/AdminMembershipRequirements.tsx
- src/components/Admin/Tabs/AdminMembershipSettings.tsx
- src/components/AgreementHome/AgreementProvider.tsx
- src/components/Profile/Tabs/Identity/AgreementMemberCard.tsx
> Background agreement transactions

- src/components/Create/CreationProgressModal.tsx
Updated API method to only mint tokens for "members". Need to specify members array here.
> add members to initial agreement creation

- src/components/Create/CreateAgreementModal.tsx
- src/components/ExtensionOnboarding/ExtensionOnboardingFlow.tsx
> fix: click outside to close create agreement modal

- package.json
- src/pages/_app.tsx
- yarn.lock
Adding google tag manager
Adds a new package for interacting with the google tag manager API
> Adding google tag manager

- src/components/Admin/AgreementAdmin.tsx
- src/components/AgreementHome/AgreementProvider.tsx
- src/components/AgreementHome/CoreWidgets/AgreementInfoWidget.tsx
- src/components/AgreementHome/CoreWidgets/AgreementRequirementsWidget.tsx
- src/components/ExtensionOnboarding/ExtensionOnboardingFlow.tsx
- src/components/Extensions/ExtensionBlankSlate.tsx
- src/components/Extensions/Symphony/SymphonyExtensionSettings.tsx
- src/components/Header/Header.tsx
- src/components/Profile/Tabs/Identity/ManageLinkedAccountModal.tsx
- src/components/Profile/Tabs/MyAgreements.tsx
- src/components/Styles/MeemTheme.tsx
- src/model/agreement/agreements.tsx
Add missing UI state for symphony onboarding flow + bug fixes
> Onboarding followup

- src/components/AgreementHome/AgreementHome.tsx
- src/components/ExtensionOnboarding/ExtensionOnboardingFlow.tsx
- src/components/Extensions/Symphony/SymphonyExtensionSettings.tsx
- src/components/Extensions/Symphony/SymphonyWidget.tsx
> feat: symphony widget for unlaunched communities

- src/components/ExtensionOnboarding/ExtensionOnboardingFlow.tsx
- src/components/Header/MeemFAQModal.tsx
> fix: update copy in meem faq and symphony onboarding

- src/components/Extensions/Symphony/SymphonyExtensionSettings.tsx
This reverts commit ba1789f22be8446b9245fb2f348b12a75eec6ca3.
> Revert "fix: symphony loading now waits for all gun data to be available"

- generated/graphql.tsx
- src/components/Admin/AgreementAdmin.tsx
- src/components/Admin/Tabs/AdminRoles.tsx
- src/components/AgreementHome/AgreementHome.tsx
- src/components/AgreementHome/CoreWidgets/AgreementAddMoreExtensionsWidget.tsx
- src/components/App.tsx
- src/components/Extensions/Symphony/SymphonyExtensionSettings.tsx
- src/components/Extensions/Symphony/SymphonyOnboardingFlow.tsx
- src/components/Extensions/Symphony/symphony.gql.tsx
- src/components/Header/Header.tsx
- src/components/Profile/Profile.tsx
- src/components/Roles/RolesManager.tsx
> More symphony improvements

- src/pages/_app.tsx
- yarn.lock
Added the Zoho ASAP help widget
Zoho script to load the meem zoho help widget
> add zoho help widget to website

- src/components/Extensions/Symphony/SymphonyOnboardingFlow.tsx
- src/pages/_app.tsx
- src/pages/onboard/symphony.tsx
Adding custom GTM events to symphony onboarding
> Add custom gtm events to onboarding

- src/components/Create/CreateAgreementModal.tsx
- src/components/Extensions/AddExtensionModal.tsx
- src/components/Extensions/Symphony/SymphonyExtension.tsx
- src/components/Extensions/Symphony/SymphonyOnboardingFlow.tsx
- src/components/Extensions/Symphony/SymphonyRuleBuilder.tsx
- src/components/Profile/Tabs/MyAgreements.tsx
- src/components/Roles/Role/RolesManagerContent.tsx
Added additional events to Symphony onboarding/rule builder
> Add more gtm events to Symphony

- src/components/Extensions/Symphony/SymphonyExtension.tsx
- src/components/Extensions/Symphony/SymphonyOnboardingFlow.tsx
- src/components/Styles/MeemTheme.tsx
Fixed the onboarding flow so that it works again
> Symphony v2: working onboarding

- src/components/Extensions/Symphony/Modals/SymphonyInputOutputModal.tsx
- src/components/Extensions/Symphony/SymphonyExtension.tsx
- src/components/Extensions/Symphony/SymphonyOnboardingFlow.tsx
Added remaining analytics events
> Update analytics tracking

- src/components/Extensions/Symphony/Modals/SymphonyDisconnectModal.tsx
- src/components/Extensions/Symphony/Modals/SymphonyInputOutputModal.tsx
- src/components/Extensions/Symphony/RuleBuilders/SymphonySlackWebhookRuleBuilder.tsx
> Late march fixes

- src/components/Extensions/Symphony/SymphonyExtension.tsx
> Filter out connections by whether the Discord name exists

- src/components/AgreementHome/CoreWidgets/AgreementAddExtensionsWidget.tsx
- src/components/AgreementHome/CoreWidgets/AgreementInfoWidget.tsx
- src/components/AgreementHome/JoinLeaveAgreementModal.tsx
> Support leaving a contractless agreement

- src/components/AgreementHome/AgreementProvider.tsx
- src/components/AgreementHome/CoreWidgets/AgreementInfoWidget.tsx
> Fix state when leaving agreement

- src/components/Extensions/CommunityTweets/CTOnboardingFlow.tsx
> Improve 'start using CT' button responsiveness
